package com.onesignal.core.internal.models

import com.onesignal.core.internal.modeling.Model

internal class ConfigModel : Model() {
    /**
     * Interval at which the [OperationRepo] will release batches of [Operation] when not forced
     */
    var operationReleaseInterval: Double = 30.0

    /**
     * Maximum number of [Operation] allowed in the [OperationRepo] before it releases a batch
     */
    var operationSoftCap: UInt = 5u

    /**
     * Maximum number of [Operation] allowed to be released by the [OperationRepo] at once
     */
    var operationHardCap: UInt = 10u

    /**
     * Whether or not [Operation] will be written to disk
     */
    var allowOffline: Boolean = false

    /**
     * Maximum time a request monitored by [RequestController] can be in flight before error
     */
    var requestTimeout: Double = 10.0

    /**
     * Maximum time in minutes a user can spend out of focus before a new session is generated by the [SessionController]
     */
    var sessionFocusTimeout: Double = 10.0

    /**
     * Operation repo file path
     */
    var operationRepoCachePath: String = "" // todo

    /**
     * The minimum number of milliseconds required to pass to allow the fetching of IAM to occur.
     */
    var fetchIAMMinInterval: Long = 30000

    /**
     * The current AppID
     */
    var appId: String?
        get() = get(::appId.name) { null }
        set(value) { set(::appId.name, value) }

    /**
     * The current userID
     */
    var userId: String?
        get() = get(::userId.name) { null }
        set(value) { set(::userId.name, value) }

    /**
     * Whether this app requires privacy consent to send data to backend.
     */
    var requiresPrivacyConsent: Boolean
        get() = get(::requiresPrivacyConsent.name) { false }
        set(value) { set(::requiresPrivacyConsent.name, value) }
}
