package com.onesignal.debug

/**
 * Represents a log event generated by the OneSignal SDK. This is provided to
 * [ILogListener.onLogEvent] when a log message is generated.
 */
data class OneSignalLogEvent(
    /**
     * The severity level of this log event.
     */
    val level: LogLevel,
    /**
     * The log message content.
     */
    val entry: String,
)
